// Generated by cbindgen from gip-bridge's src/ffi.rs. Do not edit by hand.

#ifndef GIP_BRIDGE_H
#define GIP_BRIDGE_H

// This file is generated by cbindgen. Regenerate with `cbindgen --output include/gip_bridge.h`.

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define CMD_POWER 5

#define CMD_VIRTUAL_KEY 7

#define CMD_LED 10

#define CMD_RUMBLE 9

#define CMD_INPUT 32

#define OPT_INTERNAL (1 << 5)

#define OPT_CHUNK (1 << 7)

#define POWER_MODE_ON 0

#define LED_MODE_ON 1

#define LED_BRIGHTNESS_DEFAULT 20

/**
 * The guide/Xbox button's key code in `GIP_CMD_VIRTUAL_KEY` payloads. It is
 * reported separately from the rest of the buttons in `GIP_CMD_INPUT`.
 */
#define VKEY_GUIDE 91

/**
 * Outcome of [`gip_poll_state`].
 */
typedef enum GipPollResult {
    /**
     * A new report was parsed and written to `out`.
     */
    GipPollResult_State = 0,
    /**
     * No report arrived within the timeout; `out` was not touched. Not an
     * error - callers should just poll again.
     */
    GipPollResult_Timeout = 1,
    /**
     * The device disconnected or a USB error occurred; `out` was not
     * touched. The caller should `gip_close` and stop polling.
     */
    GipPollResult_Error = 2,
} GipPollResult;

/**
 * Opaque handle for an open, handshaken GIP controller.
 */
typedef struct GipDevice GipDevice;

typedef struct GipButtons {
    bool a;
    bool b;
    bool x;
    bool y;
    bool back;
    bool start;
    bool left_stick;
    bool right_stick;
    bool left_shoulder;
    bool right_shoulder;
    bool dpad_up;
    bool dpad_down;
    bool dpad_left;
    bool dpad_right;
    bool guide;
} GipButtons;

typedef struct GipState {
    struct GipButtons buttons;
    uint16_t trigger_left;
    uint16_t trigger_right;
    int16_t stick_left_x;
    int16_t stick_left_y;
    int16_t stick_right_x;
    int16_t stick_right_y;
} GipState;

/**
 * Finds and opens the first matching GIP controller currently connected and
 * completes the power-on handshake. Returns NULL if none is connected or
 * setup fails - safe to call again on a retry/hotplug timer.
 */
struct GipDevice *gip_open_matching_device(void);

/**
 * Blocks for up to `READ_TIMEOUT` waiting for the next `GIP_CMD_INPUT`
 * report. See [`GipPollResult`] for what each outcome means. `device` and
 * `out` must be non-null and valid for the duration of the call.
 */
enum GipPollResult gip_poll_state(struct GipDevice *device, struct GipState *out);

/**
 * Sends a rumble command to the physical controller's main motors.
 * `device` must be non-null and valid.
 */
bool gip_send_rumble(struct GipDevice *device, uint8_t left, uint8_t right);

/**
 * Frees a device opened by `gip_open_matching_device`. `device` may be
 * NULL (no-op).
 */
void gip_close(struct GipDevice *device);

/**
 * Returns the USB vendor ID of the connected controller. `device` must be
 * non-null and valid.
 */
uint16_t gip_device_vendor_id(struct GipDevice *device);

/**
 * Returns the USB product ID of the connected controller. `device` must be
 * non-null and valid.
 */
uint16_t gip_device_product_id(struct GipDevice *device);

#endif  /* GIP_BRIDGE_H */
